### ISSUE TITLE
[Question] Error while exporting my dashboard

### ISSUE THREAD

**Issue by rdelullier** [jakubplichta/grafana-dashboard-builder#168]
Hello,
I'm opening this issue because while I was trying to use your dashboard builde to creat my own graph I've faced an error during the exportation on my server.

The error is the following : 
"Traceback (most recent call last):
  File "/usr/local/bin/grafana-dashboard-builder", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/grafana_dashboards/cli.py", line 102, in main
    project_processor.process_projects(projects, context)
  File "/usr/local/lib/python3.7/dist-packages/grafana_dashboards/exporter.py", line 57, in process_projects
    processor.process_dashboard(project.name, dashboard_name, json_obj)
  File "/usr/local/lib/python3.7/dist-packages/grafana_dashboards/client/grafana.py", line 46, in process_dashboard
    self._connection.make_request('/api/dashboards/db', body)
  File "/usr/local/lib/python3.7/dist-packages/grafana_dashboards/client/connection.py", line 68, in make_request
    return {} if (response_body is None or response_body == '') else json.loads(response_body)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"

After some work on both the yaml source file and the generated json file I found that the json file was missing some parameters.

Please find attached the file before and after the line I added.

With this line I was able to POST my dashboard.json on my server.

Did you heard about this issue before ?

Thanks by advance for your time and your answer.

[JsonBefore.json.txt](https://github.com/jakubplichta/grafana-dashboard-builder/files/3525505/JsonBefore.json.txt)
[JsonAfter.json.txt](https://github.com/jakubplichta/grafana-dashboard-builder/files/3525509/JsonAfter.json.txt)

# #

**Comment by manueligno78** [comment]
Please attach the yaml file you are using, and please be more specific on your problem. Actually it is not clear (at least for me). Are you trying to parse an influxdb ds based graph?

**Comment by rdelullier** [comment]
Hello,

Sorry if I wasn’t clear enough.

Please find attached the project.yaml file I use to generate my json dashboard.

[project2.yaml.txt](https://github.com/jakubplichta/grafana-dashboard-builder/files/3529042/project2.yaml.txt)

To be more clear, I’m trying to create a new dashboard and then import it on my grafana server. But when I used the exporter “grafana” an error occurred.
Then when trying to debug the problem while using Postman to create POST request on the server, I found that in the json file the keyword “dashboard” and the corresponding bracket.

You can find this in the 2 file I joined with my issu but here is the short part of the file which is concerned :

Before the fix : 

{
  "nav": [
    {
      "type": "timepicker"
    }
  ],
    "rows": [
    {
     …
}

After the fix : 
{
  "nav": [
    {
      "type": "timepicker"
    }
  ],
  "dashboard": {
  "rows": [
    {
    …
    }
}

Thanks again for your answer.

Best Regards,

Rafaël

**Comment by manueligno78** [comment]
I cannot reproduce the issue, I have used the yaml you posted, an updated version of grafana-dashboard-builder tool and Grafana 6.0.0.

Export works fine, after export the dashboard is visible and working on Grafana.

I suggest to check if all your components are up to date.
